# This is a basic workflow to help you get started with Actions
name: CI-CD

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
jobs:
  # This workflow contains multiple jobs
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Unit Tests
        run: |
          npm test
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [20.x]

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v2

  #     - name: setup node
  #       uses: actions/setup-node@master
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     # install applicaion dependencies
  #     - name: Install dependencies
  #       run: |
  #         npm install --legacy-peer-deps
  #       working-directory: client/
  #     # build and test the apps
  #     - name: build
  #       run: |
  #         npm run build
  #       working-directory: client/
          
  push_to_Docker_Hub:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build and push Docker image
      env:
        IMAGE_TAG: ${{ format('{0}', github.run_number) }}
      run: |
        docker build . --file Dockerfile --tag rohitgoud9/deliverwise-frontend:${IMAGE_TAG}
        docker push rohitgoud9/deliverwise-frontend:${IMAGE_TAG}
  push_to_vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} 
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          vercel-args: "--prod"
